# Soal Prioritas 1

## Install Library scikit-learn untuk Transformasi Data

In [15]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\acer\appdata\local\programs\python\python39\lib\site-packages (1.2.2)
Requirement already satisfied: scipy>=1.3.2 in c:\users\acer\appdata\local\programs\python\python39\lib\site-packages (from scikit-learn) (1.10.1)
Requirement already satisfied: joblib>=1.1.1 in c:\users\acer\appdata\local\programs\python\python39\lib\site-packages (from scikit-learn) (1.2.0)
Requirement already satisfied: numpy>=1.17.3 in c:\users\acer\appdata\local\programs\python\python39\lib\site-packages (from scikit-learn) (1.24.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\acer\appdata\local\programs\python\python39\lib\site-packages (from scikit-learn) (3.1.0)

[notice] A new release of pip is available: 23.0.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip

### 1. Normalisasi Data: Normalisasi harga rumah dan harga per meter persegi menggunakan teknik Min-Max.

In [79]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler

df = pd.read_csv('./src/house_listings.csv')

# Mengubah format data pada kolom 'price'
df['price'] = df['price'].str.replace(' ', '').str.replace('.', '').astype(float)
df['price'] = df['price'].apply(lambda x: x / 1000 if x != 0 else x)

# Mengganti tanda spasi dan koma menjadi kosong dan mengubah tipe data kolom 'price_1m2' menjadi string
df['price_1m2'] = df['price_1m2'].str.replace(' ', '').str.replace(',', '').str.replace('.', '')

# Menghapus 'AZN/m²' dari kolom 'price_1m2' dan mengubah tipe data kolom tersebut menjadi float
df['price_1m2'] = df['price_1m2'].str.replace(r'(\D)', '', regex=True).astype(float)

# Membuat objek skaler dan melakukan normalisasi
scaler = MinMaxScaler()
df[['price', 'price_1m2']] = scaler.fit_transform(df[['price', 'price_1m2']])

C:\Users\ACER\AppData\Local\Temp\ipykernel_2768\4134777780.py:8: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['price'] = df['price'].str.replace(' ', '').str.replace('.', '').astype(float)
C:\Users\ACER\AppData\Local\Temp\ipykernel_2768\4134777780.py:12: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['price_1m2'] = df['price_1m2'].str.replace(' ', '').str.replace(',', '').str.replace('.', '')

In [80]:
df.head()

,category,price,currency,price_1m2,title,address,floor,area,title_deed,repair,mortgage,url,room_number
0,Köhnə tikili,0.021298,AZN,0.116922,"Satılır 3 otaqlı köhnə tikili 52 m², 8-ci kilo...",Elşən Süleymanov küç 137,7 / 9,52 m²,var,var,NaN,https://bina.az/items/3858477,3.0
1,Yeni tikili,0.030369,AZN,0.076321,"Satılır 2 otaqlı yeni tikili 102 m², Neftçilər m.",Mehdi Abbasov küçəsi,2 / 17,102 m²,yoxdur,var,NaN,https://bina.az/items/3858493,2.0
2,Köhnə tikili,0.022875,AZN,0.097588,"Satılır 2 otaqlı köhnə tikili 65 m², Nərimanov r.",Atatürk Prospekti,6 / 9,65 m²,var,var,var,https://bina.az/items/3858489,2.0
3,Köhnə tikili,0.031749,AZN,0.086471,"Satılır 3 otaqlı köhnə tikili 95 m², Gənclik m.",Atatürk pr.,4 / 9,95 m²,var,var,var,https://bina.az/items/3858491,3.0
4,Yeni tikili,0.052258,AZN,0.064720,"Satılır 3 otaqlı yeni tikili 190 m², Nəsimi r.",Möhsün Sənani küçəsi,6 / 16,190 m²,var,yoxdur,NaN,https://bina.az/items/3858488,3.0

### 2.Encoding Kategorikal: Terapkan encoding one-hot pada kolom 'Category', 'title_deed', 'repair', dan 'mortgage'.

In [81]:
from sklearn.preprocessing import OneHotEncoder

# Membuat objek OneHotEncoder dengan parameter sparse=False
encoder = OneHotEncoder(sparse=False)

#Menghapus nilai NaN atau Null
df.dropna(subset=['category', 'title_deed', 'repair', 'mortgage'], inplace=True)

# Memanggil metode fit_transform pada objek OneHotEncoder dengan kolom yang akan di-encode
encoded_columns = encoder.fit_transform(df[['category', 'title_deed', 'repair', 'mortgage']])

# Mengubah hasil fit_transform menjadi DataFrame dengan menggunakan metode get_feature_names_out()
encoded_columns = pd.DataFrame(encoded_columns, columns=encoder.get_feature_names_out())

# Menyatukan DataFrame hasil encoding dengan DataFrame asli menggunakan metode concat()
df = pd.concat([df, encoded_columns], axis=1)

# Menghapus kolom asli yang telah di-encode dari DataFrame
df.drop(['category', 'title_deed', 'repair', 'mortgage'], axis=1, inplace=True)

c:\Users\ACER\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

In [82]:
df.head()

,price,currency,price_1m2,title,address,floor,area,url,room_number,category_Köhnə tikili,category_Yeni tikili,title_deed_var,title_deed_yoxdur,repair_var,repair_yoxdur,mortgage_var
2,0.022875,AZN,0.097588,"Satılır 2 otaqlı köhnə tikili 65 m², Nərimanov r.",Atatürk Prospekti,6 / 9,65 m²,https://bina.az/items/3858489,2.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0
3,0.031749,AZN,0.086471,"Satılır 3 otaqlı köhnə tikili 95 m², Gənclik m.",Atatürk pr.,4 / 9,95 m²,https://bina.az/items/3858491,3.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0
9,0.006508,AZN,0.062787,"Satılır 2 otaqlı yeni tikili 41 m², Masazır q.",İstiqlaliyyət küçəsi,3 / 10,41 m²,https://bina.az/items/3858482,2.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0
10,0.068231,AZN,0.099521,"Satılır 4 otaqlı yeni tikili 165 m², Nərimanov r.",Yusif Vəzir Çəmənzəminli küçəsi.,4 / 16,165 m²,https://bina.az/items/3844647,4.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0
13,0.014987,AZN,0.049737,"Satılır 3 otaqlı yeni tikili 85 m², Masazır q.",Ə.Vahid küçəsi.,5 / 14,85 m²,https://bina.az/items/3768070,3.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0

### 3. Aggregasi Data: Hitung rata-rata, median, dan mode harga rumah berdasarkan jumlah kamar dan tipe bangunan.

In [83]:
df_grouped = df.groupby(['room_number', 'category_Köhnə tikili', 'category_Yeni tikili'])

# Hitung rata-rata, median, dan modus
df_aggregated = df_grouped['price'].agg(['mean', 'median', lambda x: x.mode().iloc[0]])

df_aggregated = df_aggregated.rename(columns={'<lambda_0>': 'modus'})

In [84]:
df_aggregated.head()

                                                            mean    median  \
room_number category_Köhnə tikili category_Yeni tikili
1.0         0.0                   1.0                   0.015984  0.015086
            1.0                   0.0                   0.018114  0.015973
2.0         0.0                   1.0                   0.025234  0.021692
            1.0                   0.0                   0.024225  0.021495
3.0         0.0                   1.0                   0.041320  0.039637

                                                           modus
room_number category_Köhnə tikili category_Yeni tikili
1.0         0.0                   1.0                   0.015973
            1.0                   0.0                   0.012424
2.0         0.0                   1.0                   0.017945
            1.0                   0.0                   0.020903
3.0         0.0                   1.0                   0.043581

# Soal Prioritas 2

## 1. Mengelola Nilai yang Hilang pada kolom area dan floor

In [85]:
# Menghitung jumlah nilai yang hilang pada kolom 'area'
num_missing_area = df['area'].isna().sum()

# Menghitung jumlah nilai yang hilang pada kolom 'floor'
num_missing_floor = df['floor'].isna().sum()

# Menampilkan jumlah nilai yang hilang
print(f"Jumlah nilai yang hilang pada kolom 'area': {num_missing_area}")
print(f"Jumlah nilai yang hilang pada kolom 'floor': {num_missing_floor}")

Jumlah nilai yang hilang pada kolom 'area': 7605
Jumlah nilai yang hilang pada kolom 'floor': 7605

In [86]:
# Memisahkan kolom 'floor' menjadi 'floor' dan 'total_floor'
df[['floor', 'total_floor']] = df['floor'].str.split(' / ', 1, expand=True)

# Menghapus karakter 'm²' pada kolom 'area'
df['area'] = df['area'].str.replace(' m²', '')

# Mengubah tipe data kolom 'floor', 'area', dan 'total_floor' menjadi numerik
df[['floor', 'area', 'total_floor']] = df[['floor', 'area', 'total_floor']].apply(pd.to_numeric, errors='coerce')

# Imputasi nilai yang hilang pada kolom 'area' dengan nilai rata-rata
rata_rata_area = df['area'].mean()
df['area'].fillna(rata_rata_area, inplace=True)

# Imputasi nilai yang hilang pada kolom 'floor' dengan nilai median
median_floor = df['floor'].median()
df['floor'].fillna(median_floor, inplace=True)

C:\Users\ACER\AppData\Local\Temp\ipykernel_2768\1992621073.py:2: FutureWarning: In a future version of pandas all arguments of StringMethods.split except for the argument 'pat' will be keyword-only.
  df[['floor', 'total_floor']] = df['floor'].str.split(' / ', 1, expand=True)

In [87]:
df.head()

,price,currency,price_1m2,title,address,floor,area,url,room_number,category_Köhnə tikili,category_Yeni tikili,title_deed_var,title_deed_yoxdur,repair_var,repair_yoxdur,mortgage_var,total_floor
2,0.022875,AZN,0.097588,"Satılır 2 otaqlı köhnə tikili 65 m², Nərimanov r.",Atatürk Prospekti,6.0,65.0,https://bina.az/items/3858489,2.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,9.0
3,0.031749,AZN,0.086471,"Satılır 3 otaqlı köhnə tikili 95 m², Gənclik m.",Atatürk pr.,4.0,95.0,https://bina.az/items/3858491,3.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,9.0
9,0.006508,AZN,0.062787,"Satılır 2 otaqlı yeni tikili 41 m², Masazır q.",İstiqlaliyyət küçəsi,3.0,41.0,https://bina.az/items/3858482,2.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,10.0
10,0.068231,AZN,0.099521,"Satılır 4 otaqlı yeni tikili 165 m², Nərimanov r.",Yusif Vəzir Çəmənzəminli küçəsi.,4.0,165.0,https://bina.az/items/3844647,4.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,16.0
13,0.014987,AZN,0.049737,"Satılır 3 otaqlı yeni tikili 85 m², Masazır q.",Ə.Vahid küçəsi.,5.0,85.0,https://bina.az/items/3768070,3.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,14.0

In [89]:
df['floor']

2        6.0
3        4.0
9        3.0
10       4.0
13       5.0
        ...
11204    8.0
11205    8.0
11206    8.0
11207    8.0
11208    8.0
Name: floor, Length: 18814, dtype: float64

In [90]:
df['area']

2         65.000000
3         95.000000
9         41.000000
10       165.000000
13        85.000000
            ...
11204    110.075627
11205    110.075627
11206    110.075627
11207    110.075627
11208    110.075627
Name: area, Length: 18814, dtype: float64

In [91]:
df['area'].isna().sum()

0

In [92]:
df['floor'].isna().sum()

0

## 2. Mengatasi Outlier

In [94]:
# Menampilkan informasi tambahan setelah menghapus outlier
print("Informasi sebelum menghapus outlier:")
df.head()

Informasi sebelum menghapus outlier:

,price,currency,price_1m2,title,address,floor,area,url,room_number,category_Köhnə tikili,category_Yeni tikili,title_deed_var,title_deed_yoxdur,repair_var,repair_yoxdur,mortgage_var,total_floor
2,0.022875,AZN,0.097588,"Satılır 2 otaqlı köhnə tikili 65 m², Nərimanov r.",Atatürk Prospekti,6.0,65.0,https://bina.az/items/3858489,2.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,9.0
3,0.031749,AZN,0.086471,"Satılır 3 otaqlı köhnə tikili 95 m², Gənclik m.",Atatürk pr.,4.0,95.0,https://bina.az/items/3858491,3.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,9.0
9,0.006508,AZN,0.062787,"Satılır 2 otaqlı yeni tikili 41 m², Masazır q.",İstiqlaliyyət küçəsi,3.0,41.0,https://bina.az/items/3858482,2.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,10.0
10,0.068231,AZN,0.099521,"Satılır 4 otaqlı yeni tikili 165 m², Nərimanov r.",Yusif Vəzir Çəmənzəminli küçəsi.,4.0,165.0,https://bina.az/items/3844647,4.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,16.0
13,0.014987,AZN,0.049737,"Satılır 3 otaqlı yeni tikili 85 m², Masazır q.",Ə.Vahid küçəsi.,5.0,85.0,https://bina.az/items/3768070,3.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,14.0

In [95]:
# Menghitung kuartil pertama (Q1), kuartil ketiga (Q3), dan IQR (Interquartile Range)
Q1 = df['price'].quantile(0.25)
Q3 = df['price'].quantile(0.75)
IQR = Q3 - Q1

# Mengidentifikasi outlier
outlier_index = df[(df['price'] < (Q1 - 1.5 * IQR)) | (df['price'] > (Q3 + 1.5 * IQR))].index

# Menghapus outlier
df_cleaned = df.drop(outlier_index)

In [96]:
print("\nInformasi setelah menghapus outlier:")
df_cleaned

Informasi setelah menghapus outlier:

,price,currency,price_1m2,title,address,floor,area,url,room_number,category_Köhnə tikili,category_Yeni tikili,title_deed_var,title_deed_yoxdur,repair_var,repair_yoxdur,mortgage_var,total_floor
2,0.022875,AZN,0.097588,"Satılır 2 otaqlı köhnə tikili 65 m², Nərimanov r.",Atatürk Prospekti,6.0,65.000000,https://bina.az/items/3858489,2.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,9.0
3,0.031749,AZN,0.086471,"Satılır 3 otaqlı köhnə tikili 95 m², Gənclik m.",Atatürk pr.,4.0,95.000000,https://bina.az/items/3858491,3.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,9.0
9,0.006508,AZN,0.062787,"Satılır 2 otaqlı yeni tikili 41 m², Masazır q.",İstiqlaliyyət küçəsi,3.0,41.000000,https://bina.az/items/3858482,2.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,10.0
10,0.068231,AZN,0.099521,"Satılır 4 otaqlı yeni tikili 165 m², Nərimanov r.",Yusif Vəzir Çəmənzəminli küçəsi.,4.0,165.000000,https://bina.az/items/3844647,4.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,16.0
13,0.014987,AZN,0.049737,"Satılır 3 otaqlı yeni tikili 85 m², Masazır q.",Ə.Vahid küçəsi.,5.0,85.000000,https://bina.az/items/3768070,3.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,14.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11204,NaN,NaN,NaN,NaN,NaN,8.0,110.075627,NaN,NaN,0.0,1.0,1.0,0.0,1.0,0.0,1.0,NaN
11205,NaN,NaN,NaN,NaN,NaN,8.0,110.075627,NaN,NaN,0.0,1.0,1.0,0.0,1.0,0.0,1.0,NaN
11206,NaN,NaN,NaN,NaN,NaN,8.0,110.075627,NaN,NaN,0.0,1.0,1.0,0.0,1.0,0.0,1.0,NaN
11207,NaN,NaN,NaN,NaN,NaN,8.0,110.075627,NaN,NaN,1.0,0.0,1.0,0.0,1.0,0.0,1.0,NaN
11208,NaN,NaN,NaN,NaN,NaN,8.0,110.075627,NaN,NaN,0.0,1.0,1.0,0.0,1.0,0.0,1.0,NaN

In [97]:
print("\nIndeks outlier yang dihapus:")
print(outlier_index)

Indeks outlier yang dihapus:
Int64Index([  140,   169,   222,   256,   297,   314,   331,   345,   376,
              530,
            ...
            34562, 34634, 34914, 35034, 35081, 35082, 35100, 35302, 35345,
            35390],
           dtype='int64', length=533)

## 3. Integritas Data

In [100]:
# Verifikasi dan validasi kolom 'address'
# Pastikan semua nilai adalah string sebelum memeriksa karakter pertama
df['address_valid'] = df['address'].astype(str).apply(lambda x: x[0].isupper())

# Verifikasi dan validasi kolom 'url'
# Pastikan semua nilai adalah string sebelum memeriksa karakter pertama
df['url_valid'] = df['url'].astype(str).apply(lambda x: x.startswith('https://'))

In [101]:
# Menampilkan dataframe dengan kolom verifikasi dan validasi
print("Dataframe setelah verifikasi dan validasi:")
df.head()

Dataframe setelah verifikasi dan validasi:

,price,currency,price_1m2,title,address,floor,area,url,room_number,category_Köhnə tikili,category_Yeni tikili,title_deed_var,title_deed_yoxdur,repair_var,repair_yoxdur,mortgage_var,total_floor,address_valid,url_valid
2,0.022875,AZN,0.097588,"Satılır 2 otaqlı köhnə tikili 65 m², Nərimanov r.",Atatürk Prospekti,6.0,65.0,https://bina.az/items/3858489,2.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,9.0,True,True
3,0.031749,AZN,0.086471,"Satılır 3 otaqlı köhnə tikili 95 m², Gənclik m.",Atatürk pr.,4.0,95.0,https://bina.az/items/3858491,3.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,9.0,True,True
9,0.006508,AZN,0.062787,"Satılır 2 otaqlı yeni tikili 41 m², Masazır q.",İstiqlaliyyət küçəsi,3.0,41.0,https://bina.az/items/3858482,2.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,10.0,True,True
10,0.068231,AZN,0.099521,"Satılır 4 otaqlı yeni tikili 165 m², Nərimanov r.",Yusif Vəzir Çəmənzəminli küçəsi.,4.0,165.0,https://bina.az/items/3844647,4.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,16.0,True,True
13,0.014987,AZN,0.049737,"Satılır 3 otaqlı yeni tikili 85 m², Masazır q.",Ə.Vahid küçəsi.,5.0,85.0,https://bina.az/items/3768070,3.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,14.0,True,True